### PR TITLE
Fix gitmate's complain

### PR DESCRIPTION
**Pull request by 9r0x**
This fixes broken ci, and avoids gitmate's complain

I think .coafile is only needed for functioning code in this repo, so I excluded python's config and injected it manually each time ci is running.

### Checklist

- [√] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [√] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by jayvdb** [comment]
What is the problem that you are trying to solve ?
Which issue ?

**Comment by 9r0x** [comment]
There is a problem with gitmate as it is checking the test python file, see pr https://github.com/coala/coala-emacs/pull/18
So I removed python setting in .coafile

**Comment by 9r0x** [comment]
Also the badge in readme is showing error, I guess my pr will solve it. 
After this pr, later I will try to add coala checker to default emacs checker

**Comment by jayvdb** [comment]
https://github.com/coala/coala-emacs/pull/18 is red because a maintainer flagged it for needing improvement, not a build failure.

https://travis-ci.org/coala/coala-emacs/builds/255744435 did fail.  That was https://github.com/coala/coala-emacs/pull/17

**Review by jayvdb — COMMENTED** [review]
This is not the solution.  This is breaking our CI more.
Please finish your other PRs.

**Comment by jayvdb** [comment]
No, this is a difficult problem, and you need to finish the newcomer process.

**Pull request closed without merging**
