### PR TITLE
coala-emacs: Add .editorconfig

### PR DESCRIPTION
**Pull request by kiy4h**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Review by jayvdb — CHANGES_REQUESTED** [review]
This task requires editing .moban.yaml

**Review by SerekKiri — CHANGES_REQUESTED** [review]
I think you should add this [issue](https://github.com/coala/coala-emacs/issues/21) to commit body as ```Closes https://github.com/coala/coala-emacs/issues/21```
at the bottom
Edit: I confused PR with commit but it does not bother to add to PR 😄

**Review by ksdme — APPROVED** [review]

**Comment by ksdme** [comment]
@Kiy4h Please remember to use a separate branch instead of `master` before working on your stuff. It is acceptable for this PR but keep this in mind for the subsequent tasks.

**Comment by kiy4h** [comment]
@ksdme Okay, I'll do this next time. Thanks!

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-emacs/pull/29/commits/97ff032a8dbbff8773375180d7891c14af5c2e44

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
